version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: TbQq9JHBI*YGTB9F
      POSTGRES_DB: customer-management
    networks:
      - app-network
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: kamilli818@gmail.com
      PGADMIN_DEFAULT_PASSWORD: TbQq9JHBI*YGTB9F
    networks:
      - app-network
    restart: unless-stopped
  customer-management:
    container_name: customer-management-container
    image: customer-management
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      app-network:
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/customer-management
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: TbQq9JHBI*YGTB9F

networks:
  app-network:
    driver: bridge

volumes:
  postgres:
  pgadmin:

