spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customer-management
    username: admin
    password: TbQq9JHBI*YGTB9F
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    web:
      pageable:
        one-indexed-parameters: true
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false





server:
  port: 8080


